---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: a-team-app-of-apps
  namespace: a-team
spec:
  destination:
    namespace: a-team
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: app-of-apps/a-team
    directory:
      include: "*.yaml"
    repoURL: https://github.com/eformat/argocd-avp-sops-teams.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - Validate=true
