{{- if .Values.route.enabled -}}
{{- $fullName := include "welcome.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "welcome.labels" . | nindent 4 }}
spec:
  port:
    targetPort: {{ $svcPort }}
  to:
    kind: Service
    name: {{ $fullName }}
    weight: 100
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - status: 'True'
          type: Admitted
{{ end }}
