---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: welcome
          command:
            - "./hello.sh"
            - "from Mike"
