---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sops-secret-message
  namespace: a-team
spec:
  destination:
    namespace: a-team
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: secrets/a-team
    repoURL: https://github.com/eformat/argocd-avp-sops-teams.git
    targetRevision: main
    plugin:
      name: sops-age-plugin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
