---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: welcome-sops-helm
  namespace: a-team
spec:
  destination:
    namespace: a-team
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: https://github.com/eformat/argocd-avp-sops-teams.git
    path: applications/welcome/chart
    targetRevision: main
    plugin:
      name: sops-age-helm-plugin
      env:
        - name: HELM_VALUES
          value: |
            message: <path:welcome-sops-helm/values.enc#message>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
