---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: welcome-helm-novault
  namespace: b-team
spec:
  destination:
    namespace: b-team
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: https://github.com/eformat/argocd-avp-sops-teams.git
    path: applications/welcome/chart
    targetRevision: main
    plugin:
      name: helm-novault-plugin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
