---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: welcome-sops-kustomize
  namespace: b-team
spec:
  destination:
    namespace: b-team
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: https://github.com/eformat/argocd-avp-sops-teams.git
    path: applications/welcome/overlay/b-team/welcome-sops-kustomize
    targetRevision: main
    plugin:
      name: sops-age-kustomize-plugin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
